# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
#source 'https://github.com/TianQiLi/TQRepo.git'
 platform :ios, '12.0'

target 'TQPDFReaderDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TQPDFReaderDemo
  # pod 'TQPDFReader' , :path => './TQPDFReader'
	 
pod 'TQPDFReader-local' ,:path => './../'
#pod 'TQPDFReader'

end
